language: ruby
rbenv:
- 2.7.2
addons:
  postgresql: 9.6
install:
- bundle install
- bundle update
env:
  global:
    secure: IADFIhL0JhGNmt2Ve4cw87DlCE/r+oj22r5qSNdEZMqiaslwTq3D4VYnKiNnbfOtq0z3RMr6E3zg6PPuVhPzZHxNTjmIx7FiyB2XiuuMeuRzXb8gBtpp4kUZmOQ+afL94ZfZviEgzgNAvoytxSy2BFv4+dFbD0ZXMxpz2vQikK7uJzcyOW+r4xt6gmhEJ5d6LL1NMVKsS7cFx971lJ0RAHURpz3B5U8q5VZDzyazlhdCt4BFBetuoFoj3EyAsGxJJgKybBWO6CfRrlPGO4JaN2TfLnlTUh4pIRoeI5NkIiITTavsW/T4664Ss+KlLOdPeTFH21KH493lcx8IEyPIeDBoSEwgYpfHUsF0b0Kalo51OY2aYFg2qAS2adVbhZfjD8l5zyQLwQR3e/Cix/NOxKNQKZunLwrFU89bd4MrTFic2JC9+GcsWFNvC+KWV6I9bB2PPR96XV3N03PEgLXsMyCUkHI8/kegmsMWIAw7nSxdJFsHznijaIZSgFelX296QaCL8NrUSwSf7ViFwP+KYQsOzOh+d7JkwUa/6r8odhkDiixspwrZRXRGImuqJNImbXoP5dzKcpsC2d1kA+Lq/u5xNGr2LfctioTiYkkE8HIv+HWWXQ2v/A59tYPUSxOC/7+xpythQPe0ySHc/gzMzLJgXVXrJIMkh7tk6xah/RI=
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: K5VRz4blQn3szQjpBnaUCD8b4B8ciwKklDm/Ah92D0RMgaBsWUt7LDF7aFHuC8ESlyV8IDHIp1Vi4/WoPBNz5j2u0KgpNx3lzyEXxMxHOpNYM0x2TG5G+XX3eFqfZDgUfUYqgP5gGpgyHaqovk8ZZ56PFrm/FLoTAy2DWWB5Sydi4pXnaF7sKlMIm6itc7ns7J68L0ylyrm+kaC+ZTJPXWjAsy7DRlSIwFUKokwiMy41O12xutxmICo8BN5C+8Z2sTFJM3zEstqwpsNHmkk+GbUpXya4C6RoeYhM+2rfF8nPhAyLkGrZrvVrVpT0DFmQOwvlbx+5qGmPWC4KtIW8317ZnwmvxYT5YJbxOyDBLmJA7oB/JDtK91K+ZDQikrVtUK24n1Ne5vb+Un70RoBeK3KWKNALJmx2+hEqCe2jGEpuMeQnPX0bonFyaKxWWXy23YSRVOY2nbLBPhzndnje2KU403OepsUO2bUiSaZbaMX2IKX8pSAX8ONLKVuErS0+4t6/Of+D2unwUh5NE3k4i5lTncBqYpvNRk/V/LUIGj/LmH9GVLbthsw8ACvsNhxpz/ygMWRmK9C7tC3QM9egiau4zLUC4AROAgi5bNMpw2fP/RIuKqoozBQD1gXHuUw8qhA5dZNozZu5teJirom5dkRSpzlYXRoxFXnIlyrIAfo=
  app: protected-bastion-44831
  run: rails db:migrate
