language: ruby
rbenv:
- 2.7.2
addons:
  postgresql: 9.6
install:
- bundle install
- bundle update
env:
  global:
  - secure: NQONXXMGAmnsgKYXbed8ysCV43qFC+1Y4UwALF1/I0+t6GD/z0Q61o8xn73pc2kU440w0unr1Inibn/RZtcC74AL4Q7jqpp+M8SGT25EUUqLnA5ot2qSjD2kGlXsKZe116umKIsvKtslsIxPyztdDmmLVhQeh4lz1S0pITlx3tnnYNUUNe7TRiWeaodflFt/YUI7XSgmw1SAM91nx4/LKgV5CGKHZSsmI4Yvj7nw5/PIATsCCE6xjgx/GG4n+qseSdPlPtATrjsJrLaFWrYzZXoUH6Fq7wfm1CwSac01f/5Dz9IfEl+vI0BwtertdbUB3Ewo0uvUXmvb2YQMJfI679OztJW95ouYG4vzJdXoGdJmAIMudhdV35+g8SrfnrbC14k4Sr9mbgUC+Id+SPBj1gFEabwcFVDuX9uz2X5YUB66KnDIxVzjB1Fn9z/VujNrXRyNKyAXMblLe6LL2WMdFxZfTX+eNourDYRslX9wP4Knx4pSvUpdeN2poJF3IU2QhEdNr14fs2lG9wctVmUsJjoa50ryiElgPAiqIyybFyBPfVmoqLJWRnpfBfOXmjUb4qg3BAMsRoQ/xBBbIUBALsD1c2KWBLw27GIa4iMq4bXeMXCbflqP6iePL4guDuuzdJeGPr8ieelI68K7IA6l5xA5TI+n8Q72VsUysER0zJ0=
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: K5VRz4blQn3szQjpBnaUCD8b4B8ciwKklDm/Ah92D0RMgaBsWUt7LDF7aFHuC8ESlyV8IDHIp1Vi4/WoPBNz5j2u0KgpNx3lzyEXxMxHOpNYM0x2TG5G+XX3eFqfZDgUfUYqgP5gGpgyHaqovk8ZZ56PFrm/FLoTAy2DWWB5Sydi4pXnaF7sKlMIm6itc7ns7J68L0ylyrm+kaC+ZTJPXWjAsy7DRlSIwFUKokwiMy41O12xutxmICo8BN5C+8Z2sTFJM3zEstqwpsNHmkk+GbUpXya4C6RoeYhM+2rfF8nPhAyLkGrZrvVrVpT0DFmQOwvlbx+5qGmPWC4KtIW8317ZnwmvxYT5YJbxOyDBLmJA7oB/JDtK91K+ZDQikrVtUK24n1Ne5vb+Un70RoBeK3KWKNALJmx2+hEqCe2jGEpuMeQnPX0bonFyaKxWWXy23YSRVOY2nbLBPhzndnje2KU403OepsUO2bUiSaZbaMX2IKX8pSAX8ONLKVuErS0+4t6/Of+D2unwUh5NE3k4i5lTncBqYpvNRk/V/LUIGj/LmH9GVLbthsw8ACvsNhxpz/ygMWRmK9C7tC3QM9egiau4zLUC4AROAgi5bNMpw2fP/RIuKqoozBQD1gXHuUw8qhA5dZNozZu5teJirom5dkRSpzlYXRoxFXnIlyrIAfo=
  app: protected-bastion-44831
  run: rails db:migrate
