language: ruby
rbenv:
- 2.7.2
addons:
  postgresql: 9.6
install:
- bundle install
- bundle update
env:
  global:
  - secure: pk0blQXwLaCuz/C3Ztbkbtzv4iQsvDMo/DWFh4NoS+hGleiSUnBO2TEFdT9lwNK8RaKylNXj7Ayu2hCwP2xXU5vodZqVfJWX912i63WOnNogV/0kFVbMgPv+f1jIXITlOiu5MtM4NxZHCXIE/3EgROrCBxL0OC4mDIXyEwc5AEBRfEIXhBDtbK3EDbJxdLJA3P+VdTst5C/VR+AdCHCp5xNU/+S5BymXX/Yg5ojFHfuK+siteGBKfEwJ+E5GjcqvtEh4tR7nvfYJLrOoFUtFcLghP/NoXIR7B3LKtA1a8qJOAEuKszK2Mi+KKztD/X6s0pibl2a+LFrHVkKvIMXwD6KCO4FOFrqaAdOn22TOdE9OqhjuPhDXqT8PsMSN9DGlPaGmo6lrcxm79AZUHzc6SSSiXJF/gOpKzK27MF62X8p3GjhEs/1bjAhJAsibU0oGO79dGAEGxnUzFpKtddV0sTQ1oZnNkny5cya9WOjtKAczv9OPxKNnP9M4xA/AiyqKgGf6bdR2CeTgmfZoYzPwcbhic9RqIq1xSD+DV21GdXVlg9slUDb2pUAJ6szjeaq99spQxn4VxAja8Msnuh8lq56Mz75aJqNPZpfM4Y8jP5uKzt9NbK0NhwVEidpN+i6Akjjlk8gCODAl8faJ8NnC8MLWRUZBIE5vHLKrrTX+GQ8=
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: K5VRz4blQn3szQjpBnaUCD8b4B8ciwKklDm/Ah92D0RMgaBsWUt7LDF7aFHuC8ESlyV8IDHIp1Vi4/WoPBNz5j2u0KgpNx3lzyEXxMxHOpNYM0x2TG5G+XX3eFqfZDgUfUYqgP5gGpgyHaqovk8ZZ56PFrm/FLoTAy2DWWB5Sydi4pXnaF7sKlMIm6itc7ns7J68L0ylyrm+kaC+ZTJPXWjAsy7DRlSIwFUKokwiMy41O12xutxmICo8BN5C+8Z2sTFJM3zEstqwpsNHmkk+GbUpXya4C6RoeYhM+2rfF8nPhAyLkGrZrvVrVpT0DFmQOwvlbx+5qGmPWC4KtIW8317ZnwmvxYT5YJbxOyDBLmJA7oB/JDtK91K+ZDQikrVtUK24n1Ne5vb+Un70RoBeK3KWKNALJmx2+hEqCe2jGEpuMeQnPX0bonFyaKxWWXy23YSRVOY2nbLBPhzndnje2KU403OepsUO2bUiSaZbaMX2IKX8pSAX8ONLKVuErS0+4t6/Of+D2unwUh5NE3k4i5lTncBqYpvNRk/V/LUIGj/LmH9GVLbthsw8ACvsNhxpz/ygMWRmK9C7tC3QM9egiau4zLUC4AROAgi5bNMpw2fP/RIuKqoozBQD1gXHuUw8qhA5dZNozZu5teJirom5dkRSpzlYXRoxFXnIlyrIAfo=
  app: protected-bastion-44831
  run: rails db:migrate
